language: python
sudo: false
matrix:
    include:
        - python: 2.7
        - python: 3.4
        - python: 3.6
addons:
  apt:
    packages:
    - libhdf5-serial-dev 
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install numpy
# command to run tests, e.g. python setup.py test
script:
  nosetests test/unittests --with-coverage --cover-package=nineml
after_success:
  coveralls
