language: python
sudo: false
matrix:
    include:
        - python: 2.7
        - python: 3.3
        - python: 3.6
addons:
  apt:
    packages:
    - libhdf5-serial-dev 
install:
  - pip install -e .[hdf5]
  - pip install numpy coveralls
script:
  nosetests test/unittests --with-coverage --cover-package=nineml
after_success:
  coveralls
