import unittest
from nineml.abstraction.componentclass.visitors.queriers import (ComponentDimensionResolver)
from nineml.utils.testing.comprehensive import instances_of_all_types
from nineml.exceptions import (NineMLNameError)


class TestComponentDimensionResolverExceptions(unittest.TestCase):

    @unittest.skip('Skipping autogenerated unittest skeleton')
    def test_find_element_ninemlnameerror(self):
        """
        line #: 238
        message: '{}' element was not found in component class '{}'

        context:
        --------
    def find_element(self, sym):
        name = Expression.symbol_to_str(sym)
        element = None
        for context in reversed(self.contexts):
            try:
                element = context.parent.element(
                    name, nineml_children=self.visit_as_class.nineml_children)
            except KeyError:
                pass
        if element is None:
        """

        componentdimensionresolver = next(instances_of_all_types['ComponentDimensionResolver'].itervalues())
        self.assertRaises(
            NineMLNameError,
            componentdimensionresolver.find_element,
            sym=None)

